# Generated by Django 3.0.3 on 2020-06-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('programID', models.AutoField(primary_key=True, serialize=False)),
                ('programTitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('noteID', models.AutoField(primary_key=True, serialize=False)),
                ('noteTitle', models.TextField()),
                ('publisher', models.TextField(default='Unknow')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Program'),
        ),
    ]
